import argparse, sys
from .parser import DartClass
from .dartgen import genclass

def main():
    p = argparse.ArgumentParser()
    p.add_argument('path', help="json spec to generate")
    p.add_argument('-o', '--output', default='-', help="destination file (default stdout)")
    args = p.parse_args()

    classes = DartClass.parse_file(open(args.path))
    outfile = sys.stdout if args.output == '-' else open(args.output, 'w')
    outfile.write('// generated by dartjsonclass (todo date + git sha)\n')
    names = [cls.name for cls in classes]
    for cls in classes:
        outfile.write(genclass(cls, names))
        outfile.write('\n')

if __name__ == '__main__':
    main()
