on: [push]
jobs:
  python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: deps
      run: pip install -e .[test]
    - name: test
      # todo: coverage pls
      run: pytest
    - name: render example
      run: make lib/example.dart
    - uses: actions/upload-artifact@master
      with:
        name: example.dart
        path: lib/example.dart
  dart:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dart-lang/setup-dart@v1.3
    - name: deps
      run: dart pub get
    - uses: actions/download-artifact@master
      with:
        name: example.dart
        path: lib/example.dart
    - name: test
      run: dart test
